services:
  api:
    image: ghcr.io/abuqaiselegant/ai-agent-api:latest   # optional tag for consistency
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: ai-agent-api
    ports: ["8000:8000"]
    env_file: [.env]
    environment:
      - CORS_ORIGINS=http://localhost:8501,http://127.0.0.1:8501
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  ui:
    image: ghcr.io/abuqaiselegant/ai-agent-ui:latest    # optional tag for consistency
    build:
      context: ./ui
    container_name: ai-agent-ui
    ports: ["8501:8501"]
    environment:
      - API_BASE_URL=http://api:8000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
