name: Build & Push Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  api:
    name: Build & Push API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: |
            ghcr.io/abuqaiselegant/ai-agent-api:latest
            ghcr.io/abuqaiselegant/ai-agent-api:${{ github.sha }}

  ui:
    name: Build & Push UI
    runs-on: ubuntu-latest
    needs: api
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .                # <— repo root
          file: ui/Dockerfile       # <— explicit path
          push: true
          tags: |
            ghcr.io/abuqaiselegant/ai-agent-ui:latest
            ghcr.io/abuqaiselegant/ai-agent-ui:${{ github.sha }}
